services:
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    volumes:
      - "data:/data/db"

  ollama:
    image: "ollama/ollama:latest"

  waffentrager:
    build: "."
    env_file: ".env"
    volumes:
      - "./config.yaml:/etc/waffentrager/config.yaml"

volumes:
  data:
